In [1]:
import torch

In [6]:
# Make a 3x3 filled with 0s

# Literal approach
a = torch.tensor([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])

# Easier
a = torch.zeros(3, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# Make a 3x3 filled with 1s

b = torch.ones(3, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# Concatenate a and b on the 1st dimension to produce a 3x6 matrix

c = torch.cat((a, b), dim=1)
c

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [16]:
c.shape

torch.Size([3, 6])

In [18]:
c.type()

'torch.FloatTensor'

In [25]:
c = c.long()

# or 

c = c.type(dtype=torch.LongTensor)
c

tensor([[0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1]])

In [32]:
# PyTorch represents images as a tensor with 3 dimensions
# channel x height x width
img = torch.rand(3, 100, 100)
img.shape

torch.Size([3, 100, 100])

In [33]:
img

tensor([[[0.0939, 0.4959, 0.5313,  ..., 0.1051, 0.2328, 0.6611],
         [0.4308, 0.1249, 0.2520,  ..., 0.7523, 0.5712, 0.0214],
         [0.9114, 0.9306, 0.5729,  ..., 0.9120, 0.0092, 0.5146],
         ...,
         [0.1803, 0.4534, 0.3630,  ..., 0.1772, 0.8702, 0.2756],
         [0.7945, 0.2726, 0.5964,  ..., 0.7254, 0.3546, 0.3451],
         [0.7370, 0.9961, 0.8908,  ..., 0.7685, 0.9491, 0.9256]],

        [[0.3904, 0.3857, 0.2706,  ..., 0.1812, 0.4535, 0.2277],
         [0.4718, 0.3697, 0.4656,  ..., 0.1323, 0.1714, 0.8483],
         [0.6927, 0.6546, 0.3966,  ..., 0.8687, 0.2491, 0.4711],
         ...,
         [0.6487, 0.6961, 0.4880,  ..., 0.8568, 0.5677, 0.3053],
         [0.0947, 0.7505, 0.8424,  ..., 0.9710, 0.2966, 0.0805],
         [0.1251, 0.6955, 0.4681,  ..., 0.3674, 0.3252, 0.1034]],

        [[0.6329, 0.7155, 0.3706,  ..., 0.4364, 0.1473, 0.4221],
         [0.0530, 0.1038, 0.8266,  ..., 0.9873, 0.9957, 0.2752],
         [0.4814, 0.7250, 0.0745,  ..., 0.2691, 0.1484, 0.

In [40]:
torch.mean(img)
# or
img.mean()

tensor(0.4970)

In [41]:
torch.std(img)
# or 
img.std()


tensor(0.2871)

In [42]:
torch.median(img)

tensor(0.4953)

In [43]:
torch.mode(img)

torch.return_types.mode(
values=tensor([[5.3146e-02, 3.6741e-03, 7.4947e-03, 6.7872e-03, 4.0441e-03, 1.3094e-02,
         2.2010e-02, 9.8827e-03, 1.4120e-02, 3.8673e-03, 3.1267e-03, 1.6348e-02,
         5.0632e-03, 1.2922e-02, 3.5696e-03, 8.9815e-03, 2.2722e-03, 1.9938e-03,
         5.6347e-03, 6.0365e-03, 1.2102e-03, 3.0981e-02, 3.7671e-02, 1.7322e-02,
         2.3771e-02, 1.0521e-02, 8.0303e-03, 4.4245e-03, 2.0504e-02, 5.5212e-04,
         2.2148e-03, 4.2952e-03, 3.7426e-03, 3.8967e-03, 1.4767e-02, 7.7048e-03,
         2.2282e-02, 4.6861e-03, 1.1913e-03, 3.5605e-02, 1.4973e-04, 8.3589e-03,
         3.2187e-06, 4.8358e-03, 1.2163e-03, 7.8974e-03, 8.4371e-03, 7.7667e-03,
         3.7236e-03, 5.8969e-02, 9.9939e-04, 2.2832e-02, 3.4614e-02, 2.0471e-02,
         4.0955e-03, 3.3033e-02, 2.7064e-03, 1.3645e-02, 8.7603e-03, 4.0746e-04,
         2.1608e-02, 1.1521e-02, 1.3975e-02, 6.3226e-03, 1.3320e-03, 2.9185e-03,
         1.1907e-03, 1.5157e-02, 1.3152e-02, 8.2840e-03, 3.2142e-03, 3.3464e-

In [44]:
img.matrix_power(3)

tensor([[[1274.2089, 1236.5096, 1226.4691,  ..., 1136.5312, 1230.3173,
          1224.9142],
         [1282.5632, 1243.5696, 1237.0586,  ..., 1153.5182, 1240.6760,
          1231.1101],
         [1156.5986, 1117.8331, 1112.4414,  ..., 1037.2280, 1119.5234,
          1110.8480],
         ...,
         [1317.9124, 1269.7064, 1265.5955,  ..., 1177.6180, 1270.3301,
          1266.0779],
         [1158.8496, 1123.9452, 1119.5171,  ..., 1038.5709, 1119.1674,
          1117.1996],
         [1346.2814, 1302.2700, 1297.3314,  ..., 1202.4971, 1299.2434,
          1295.2075]],

        [[1133.7755, 1193.8065, 1204.3883,  ..., 1220.2716, 1342.2101,
          1232.8467],
         [ 967.3394, 1022.6730, 1033.2246,  ..., 1043.0115, 1146.4484,
          1062.1323],
         [1127.1105, 1186.4563, 1201.3813,  ..., 1215.9146, 1333.3816,
          1232.5779],
         ...,
         [1193.7548, 1264.5393, 1275.0142,  ..., 1287.9462, 1413.5293,
          1308.1182],
         [1029.5505, 1085.5800, 1097.388

Overall, the basics of working with these matrices makes sense.

However, I really need to:

1. Brush up on matrices and matrix math in general (independent of tensor flow)
1. Make sure I understand the concept of a tensor. Is a tensor a single number in a matrix? Or is it an n-dimensional matrix?


Well, with regard to `2.` this is in the docs:

> A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.