In [1]:
import torch

In [2]:
# Core data type - tensor

torch.rand(10)

tensor([0.6653, 0.0554, 0.1855, 0.5939, 0.6624, 0.9459, 0.0065, 0.2591, 0.2862,
        0.6969])

In [3]:
# We just have an array of 10 random numbers
# Most of deep learning is manipulating matrices

a = torch.rand(2, 2)
b = torch.rand(2, 2)

print(a)
print(b)

tensor([[0.8971, 0.0916],
        [0.0061, 0.8907]])
tensor([[0.4245, 0.2830],
        [0.7644, 0.7652]])


In [4]:
a + b

tensor([[1.3216, 0.3745],
        [0.7704, 1.6559]])

In [6]:
# Element-wise multiplcation
a * b

tensor([[0.3808, 0.0259],
        [0.0046, 0.6815]])

In [7]:
# Matrix multiplication
a @ b

tensor([[0.4508, 0.3239],
        [0.6834, 0.6833]])

In [8]:
torch.mm(a, b) # Also matrix mult

tensor([[0.4508, 0.3239],
        [0.6834, 0.6833]])

In [12]:
torch.cat((a, b)) # concatenate

tensor([[0.8971, 0.0916],
        [0.0061, 0.8907],
        [0.4245, 0.2830],
        [0.7644, 0.7652]])

In [13]:
a.shape

torch.Size([2, 2])

In [15]:
c = torch.tensor([1.5, 0, -2, 2.2])
c.shape # Also has 4 elements, but only a single dimension so cannot concat with a or b

torch.Size([4])

In [16]:
c.view(2, 2)

tensor([[ 1.5000,  0.0000],
        [-2.0000,  2.2000]])

In [17]:
# c is unchanged
c

tensor([ 1.5000,  0.0000, -2.0000,  2.2000])

In [19]:
torch.cat((a, c.view(2, 2)))

tensor([[ 0.8971,  0.0916],
        [ 0.0061,  0.8907],
        [ 1.5000,  0.0000],
        [-2.0000,  2.2000]])

In [21]:
# In view, -1 means "as many as you need"

c.view(4, -1) # 4 rows, as many columns as we need to get the 4 rows

tensor([[ 1.5000],
        [ 0.0000],
        [-2.0000],
        [ 2.2000]])